micronaut:
  application:
    name: micronautPlayground
  environments: dev
  server:
    port: 5050


datasources:
  default:
    url: jdbc:h2:mem:devDb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2

jpa:
  default:
    entity-scan:
      packages: 'micronaut.playground'
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop




